config/routes.rb
QuriTest::Application.routes.draw do
  root to: 'pages#home'

  resources :mobile_sessions, only: [:create, :index] do
    resources :mobile_events, only: :create
  end
  namespace :admin do
    root to: 'pages#home'
  end
end

app/models/mobile_event.rb
class MobileEvent < ActiveRecord::Base
  attr_accessible :event_type, :latitude, :longitude, :timestamp

  belongs_to :mobile_session
  
  delegate :last_event_type, to: :mobile_session
  validates_presence_of :event_type, :latitude, :longitude, :timestamp
  validates :event_type, 
            inclusion: { in: ["check1", 'cancel'], message: 'Invalid Sequence - last type was start' }, 
            if: :last_type_was_start?
  validates :event_type, 
            inclusion: { in: ["check2", 'cancel'], message: 'Invalid Sequence - last type was check1'  }, 
            if: :last_type_was_check1?
  validates :event_type, 
            inclusion: { in: ["finish", 'cancel'], message: 'Invalid Sequence - last type was check2'  }, 
            if: :last_type_was_check2?

 


  after_save :session_completeness_check

  private
  def session_completeness_check
    if ["finish", "cancel"].include? self.event_type
      self.mobile_session.update_attributes!(is_validly_completed: true)
    end
  end

  def last_type_was_check2?
    last_event_type == 'check2'
  end
  def last_type_was_start?
    last_event_type == 'start'
  end
  def last_type_was_check1? 
    last_event_type == 'check1'
  end

end

app/models/mobile_session.rb
class MobileSession < ActiveRecord::Base
  attr_accessible :is_validly_completed

  has_many :mobile_events
  accepts_nested_attributes_for :mobile_events


  scope :is_completed?,   lambda { |bool| where(is_validly_completed: bool)}
  scope :incomplete,      lambda { is_completed?(false) }
  scope :complete,        lambda { is_completed?(true) }
  scope :canceled,        lambda { includes(:mobile_events).where("mobile_events.event_type=?", 'cancel')}
  scope :finished,        lambda { includes(:mobile_events).where("mobile_events.event_type=?", 'finish')}
  

  def self.session_lengths
    self.all.map(&:session_length)
  end
  def self.canceled_count_of(type)
    self.canceled.map(&:prior_to_canceled_type).count(type)
  end
  def self.create_initial_session_with_event(event_params)
    ActiveRecord::Base.transaction do
      new_session = self.create!
      new_session.mobile_events.create!(event_params)
      new_session #return the new mobile session implicitly in block
    end
  end
  def self.canceled_by(point)
    self.canceled.map do |canceled_session|
      canceled_session if canceled_session.prior_to_canceled_type == point
    end.compact
  end


  def last_event_type
    self.mobile_events.order(:created_at).last.try(:event_type)
  end
  def prior_to_canceled_type
    self.mobile_events.order(:created_at)[-2].try(:event_type)
  end
  def was_canceled
    mobile_events.pluck(:event_type).include?("cancel")
  end
  def session_length
    timestamps.max - timestamps.min
  end
  def timestamps
    self.mobile_events.order(:created_at).pluck(:timestamp)
  end
  def status
    was_canceled ? "Canceled" : "Finished" 
  end
  def session_json
    session_hash = {}
    session_hash[:id] = id
    session_hash[:status] = status
    session_hash[:session_length] = session_length
    session_hash[:last_event_type] = was_canceled ? prior_to_canceled_type : "Finished" 
    return session_hash
  end
end

app/models/session_stats.rb
class SessionStats
  def initialize(sessions)
    @sessions = sessions
  end
  def percentage_which_are(options)
    if options[:optional_filter] 
      @sessions.canceled_by(options[:optional_filter]).count / @sessions.send(options[:filter]).count.to_f
    else
      @sessions.send(options[:filter]).count / @sessions.count.to_f
    end
  end
  def mean_session_length_for(complete_or_canceled, *optional_canceled_filter)
    optional_canceled_filter = optional_canceled_filter.first if optional_canceled_filter.any?
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  def home
    @stats = SessionStats.new(MobileSession)
    @mobile_sessions = MobileSession.order(:created_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mobile_events_controller.rb
class MobileEventsController < ApplicationController
  ### to post via jquery from root path 
  ### $.post('/mobile_sessions/[someid]/mobile_events', 
           ##  {event: {latitude: 10.2, longitude: 10.2, event_type: 'start', timestamp: 0.0}}, 
           ## function(d) { console.log(d); })
  def create
     ## use find to avoid exception, expect nil if not found
    mobile_session = MobileSession.incomplete.find_by_id(params[:mobile_session_id])
    if mobile_session
      new_event = mobile_session.mobile_events.create(params[:event])
      new_event.valid? ? (render json: {status: "success"}) : (render json: {status: "error", messages: new_event.errors.values.join })
      new_event.errors.clear() # seems that i have to manually clear my errors here
    else 
      # respond to failure to find mobile session by id
      render json: {status: "failure to find mobile session by id"}
    end
  end
end

app/controllers/mobile_sessions_controller.rb
class MobileSessionsController < ApplicationController
  ### to post via jquery from root path 
  ### $.post('/mobile_sessions', 
           ##  {event: {latitude: 10.2, longitude: 10.2, event_type: 'start', timestamp: 0.0}}, 
           ## function(d) { console.log(d); })
  def create
    new_mobile_session = MobileSession.create_initial_session_with_event(params[:event])
    render json: new_mobile_session.id.to_json
  end
  def index
    @mobile_sessions = MobileSession.order(:id).map(&:session_json)

    respond_to do |f|
      f.json {render json: @mobile_sessions.to_json}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    #so there is a home page
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
  def percentage_title(options)
    if options[:optional_filter]
      "#{options[:filter].titleize} after #{options[:optional_filter].titleize}"
    else 
      options[:filter].titleize
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobile_events_helper.rb
module MobileEventsHelper
end

app/helpers/mobile_sessions_helper.rb
module MobileSessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/home.html.erb
<div class='grid_6'>
  <header><h4>Of all sessions</h4></header>
  <table class='table percentages'>
    <%= render partial: "stats/percentage", locals: {stats: @stats, options: {filter: 'finished'}} %>
     <%= render partial: "stats/percentage", locals: {stats: @stats, options: {filter: 'canceled'}} %>
  </table>
  <div class='vis'>
    <div id='status-pie' class="chart">

      
    </div>
  </div>
  <div class="clear"></div>
  <header><h4>Of canceled sessions</h4></header>
  <table class='table percentages'>
    <%= render partial: "stats/percentage", locals: {stats: @stats, options: {filter: 'canceled', optional_filter: 'start'}} %>
    <%= render partial: "stats/percentage", locals: {stats: @stats, options: {filter: 'canceled', optional_filter: 'check1'}} %>
    <%= render partial: "stats/percentage", locals: {stats: @stats, options: {filter: 'canceled', optional_filter: 'check2'}} %>
  </table>

</div>
<div class='grid_6'>
  <header><h4>Ratio of Finished to Canceled</h4></header>
  <table class='table mean_and_medians'>
    <tr>
      <th></th>
      <th>Mean</th>
      <th>Median</th>
    </tr>
    <%= render partial: "stats/session_length", locals: {mobile_sessions: MobileSession.finished, type: "Finished"} %>
    <%= render partial: "stats/session_length", locals: {mobile_sessions: MobileSession.canceled, type: "Canceled (total)"} %>
    <%= render partial: "stats/session_length", locals: {mobile_sessions: MobileSession.canceled_by('start'), type: "Canceled by Start"} %>
    <%= render partial: "stats/session_length", locals: {mobile_sessions: MobileSession.canceled_by('check1'), type: "Canceled by Check1"} %>
    <%= render partial: "stats/session_length", locals: {mobile_sessions: MobileSession.canceled_by('check2'), type: "Canceled by Check2"} %>
  </table>
</div>
<div class="clear"></div>
<div class='grid_12'>
  <div class='vis'>
    <div id='bar-chart' class="chart">
      <a class="reset" href="javascript:sessionBarChart.filterAll();dc.redrawAll();" style="display: none;">reset</a>
      <span class="reset" style="display: none;">Current filter: <span class="filter"></span>
      </span>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuriTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<div class='container_12'>
  <header id='main-header'><%= image_tag "quri_logo.png" %></header>
</div>
<div class="clear"></div>
<div class='container_12' id='main-container'>
  <%= yield %>
</div>

<script type="text/javascript">
  hljs.tabReplace = '    '; // 4 spaces
  // ... or
  hljs.tabReplace = '<span class="indent">\t</span>';

  hljs.initHighlightingOnLoad();
</script>
</body>
</html>

app/views/pages/home.html.erb
<div class='grid_12'>
  <h6>Testing the API with javascript console</h6>
  <p>In order to test the api, you can open javascript console (which for me seems to be command control j for chrome, but I have swapped some keys so that may not work for you) on this page.</p>
  <p>In the console, you can initiate a mobile session via the following command: </p>
  <pre>  <code class='javascript'> $.post('/mobile_sessions', 
           {event: {latitude: 10.2, longitude: 10.2, event_type: 'start', timestamp: 0.0}}, 
           function(d) { console.log(d); }) // this will return the id via json
  </code></pre>
  <p>You may, once a session has 'started', continue the session using the id recieved like so: </p>
  <pre>  <code class='javascript'> $.post('/mobile_sessions/:id/mobile_events', 
           {event: {latitude: 10.2, longitude: 10.2, event_type: 'check1', timestamp: 0.0}}, 
           function(d) { console.log(d); })
  </code></pre>
  <p>You will receive a json object which notifies you if your request was successful or if there was an error in processing due to an improper sequence.</p>

  <hr />
  <h6>Seeding the Database</h6>
  <p>There is a rake task to seed the database with data</p>
  <pre><code class='ruby'>
    rake db:reset
    # or 
    rake db:seed
  </code></pre>
  <p>You may access the <%= link_to "administration section via this link",  admin_root_path %></p> 

</div>

app/views/stats/_percentage.html.erb
<tr>
  <th><%= percentage_title(options) %></th>
  <td><%= number_to_percentage(stats.percentage_which_are(options)*100, precision: 1) %></td>
</tr>

app/views/stats/_session_length.html.erb
<tr>
  <th><%=content_tag :h6, type.titleize %></th>
  <% mean = mobile_sessions.map(&:session_length).mean %>
  <% median = mobile_sessions.map(&:session_length).median %>
  <td><%= distance_of_time_in_words mean %>
    <br>
    <small>(specifically <%= mean %> seconds)</small>
  </th>
  <td><%= distance_of_time_in_words mobile_sessions.map(&:session_length).median %>
<br>
    <small>(specifically <%= median %> seconds)</small>
  </td>
</tr>